"""Refactor Book models with schemas

Revision ID: 66498acb0da3
Revises: 403adac01ad1
Create Date: 2024-10-23 16:45:31.297660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66498acb0da3'
down_revision: Union[str, None] = '403adac01ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wishlists')
    op.drop_index('ix_genres_name', table_name='genres')
    op.create_unique_constraint(None, 'genres', ['name'])
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=True)
    op.drop_constraint(None, 'genres', type_='unique')
    op.create_index('ix_genres_name', 'genres', ['name'], unique=True)
    op.create_table('wishlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='wishlists_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wishlists_pkey')
    )
    op.drop_table('wishlist')
    # ### end Alembic commands ###
